### ISSUE TITLE
Výstupní JST-GH konektor

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFUSBSERIAL01#1]
zapojení konektoru by mělo umožnit přímé připojení k autopilotímu TELEMETRY konektoru. 

Pro připojení na TFMODEM zřejmě bude potřeba prokřížený JST-GH propojovací kabel.

**Comment by roman-dvorak** [comment]
Připadalo by mi užitečnější mít konektor tak, aby šlo použít přímý kabel pro propojení se zařízeními. Které se obvykle takto konfigurují. 

Pak by byla varianta mít na modulu 2 konektory. Jeden z pohledu autopilota a druhý z pohledu zařízení. Aby křížený kabel nemusel existovat.

**Comment by kaklik** [comment]
> Pak by byla varianta mít na modulu 2 konektory. Jeden z pohledu autopilota a druhý z pohledu zařízení. Aby křížený kabel nemusel existovat.

Souhlasím, dva dobře popsané konektory mi přijdou jako nejlepší řešení tohoto problému.

**Comment by kaklik** [comment]
Navrhoval bych tomu konektoru pro device říkat Peripheral connector stejně jako to dělá Pixhawk.

**Comment by kaklik** [comment]
Tohle je už vyřešené.
